"""create stations table

Revision ID: 5fd0763498dd
Revises: 
Create Date: 2026-09-19 14:47:44.473742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd0763498dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('eva_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ds100', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('federal_state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('eva_id')
    )
    op.create_index(op.f('ix_stations_name'), 'stations', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stations_name'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
