"""create trains, coaches, seats, bookings, booking_items, payments

Revision ID: d2c18a983677
Revises: 196dd67952ff
Create Date: 2026-09-19 19:09:44.317948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c18a983677'
down_revision = '196dd67952ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('origin_eva', sa.Integer(), nullable=False),
    sa.Column('destination_eva', sa.Integer(), nullable=False),
    sa.Column('departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'number', 'departure')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coaches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('train_id', sa.Uuid(), nullable=False),
    sa.Column('coach_number', sa.Integer(), nullable=False),
    sa.Column('seat_class', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('mock_provider_ref', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('coach_id', sa.Uuid(), nullable=False),
    sa.Column('seat_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('held_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('seat_id', sa.Uuid(), nullable=False),
    sa.Column('train_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_items')
    op.drop_table('seats')
    op.drop_table('payments')
    op.drop_table('coaches')
    op.drop_table('bookings')
    op.drop_table('trains')
    # ### end Alembic commands ###
